name: Build and deploy Docker container to Azure Web App - kiko

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mandelbrot4669/kikofiles:kiko_v1

      - name: 'Deploy Docker container to Azure Web App'
        uses: azure/docker-webapp-deploy-action@v1
        with:
          app-name: 'kiko'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BDB49040099A45BB9C0425CF124D5B18 }}
          images: 'mandelbrot4669/kikofiles:kiko_v1'
